# GitHub Pages Configuration
# Minimal configuration to serve static files properly

plugins:
  - jekyll-optional-front-matter

# Don't process these as Jekyll files
exclude:
  - python/__pycache__/
  - "*.pyc"
  - "*.tmp"
  - README.md