# GitHub Pages Configuration for Mathematical Notebooks Platform
# Simplified configuration to ensure proper deployment

# Use GitHub Pages default theme
theme: minima

# Site metadata  
title: "Mathematical Notebooks"
description: "Interactive browser-based mathematical playgrounds powered by Python and WebAssembly"
url: "https://litlfred.github.io"
baseurl: "/notebooks"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Plugins for GitHub Pages compatibility
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - python/__pycache__/
  - "*.pyc"
  - "*.tmp"
  - "*.py"
  - weierstrass-playground/python/
  - DEVELOPMENT.md
  - "../README.md"  # Exclude root README
  - Gemfile
  - Gemfile.lock
  - index.html.backup

# Include files that would normally be excluded
include:
  - _pages
  
# Collections (if needed for future notebooks)
collections:
  notebooks:
    output: true
    permalink: /:name/