# GitHub Pages Configuration
# Enhanced Jekyll configuration for markdown-based notebooks

plugins:
  - jekyll-optional-front-matter
  - jekyll-default-layout

# Default layout for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Don't process these files
exclude:
  - python/__pycache__/
  - "*.pyc"
  - "*.tmp"
  - weierstrass-playground/python/
  - DEVELOPMENT.md